import type { Metadata } from "next";
import Player from "./playerRoot";

export const metadata: Metadata = {
	title: "Spot-a-fly",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="text-white bg-[#121212] m-0 p-0 w-dvw h-dvh overflow-hidden">
				<Player>{children}</Player>
			</body>
		</html>
	);
}
