import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Spot-a-fly",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="text-white m-0 p-0 w-dvw h-dvh overflow-hidden">{children}</body>
		</html>
	);
}
